# This is a basic workflow to help you get started with Actions

name: generator

# Controls when the action will run. 
on:
  #schedule:
  #  - cron:  '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' #install the python needed
      #- name: Cache pip
      #  uses: actions/cache@v2
      #  with:
      #    # This path is specific to Ubuntu
      #    path: ~/.cache/pip
      #    # Look to see if there is a cache hit for the corresponding requirements file
      #    key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      #    restore-keys: |
      #      ${{ runner.os }}-pip-
      #      ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      #- name: execute py script # run the run.py to get the latest data
        #run: |
          #python generator.py
        #env:
          #INSTA_PASSWORD: ${{ secrets.INSTA_PASSWORD }}
      #- name: Add & Commit
        #uses: EndBug/add-and-commit@v7.0.0
